# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
import easygui


ui = None
imagePath = None
contours = None

def connectionTest():
    print("Connection Test")
    #TODO

def openImage():
    global imagePath
    imagePath = easygui.fileopenbox()
    pix = QtGui.QPixmap(imagePath)
    lable = QtWidgets.QLabel(ui.beforeImage)
    lable.setPixmap(pix.scaled(371, 441, QtCore.Qt.KeepAspectRatio))
    lable.setScaledContents(True)
    lable.show()

def processImage():
    if(imagePath is not None):
        temp = cv2.imread(imagePath, cv2.IMREAD_UNCHANGED)
        blur = cv2.blur(temp, (5, 5))
        canny = cv2.Canny(blur, 30, 150)
        global contours
        contours, _ = cv2.findContours(canny, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        cv2.drawContours(canny, contours, -1, 255, 2)
        canny = 255 - canny
        cv2.imwrite('out.jpg', canny)

        pix = QtGui.QPixmap('out.jpg')
        lable = QtWidgets.QLabel(ui.afterImage)
        lable.setPixmap(pix.scaled(371, 441, QtCore.Qt.KeepAspectRatio))
        lable.setScaledContents(True)
        lable.show()
        print("Process Image")


def tweakImage():
    print("Tweak Image")
    #TODO

def drawImage():
    print("Draw Image")
    averages = []
    moves = []

    for contour in contours:
        averages.append(cv2.mean(contour))

    #Fix argmin issue
    currentMove = 0
    for point in averages:
        distances = []
        for point2 in averages:
            if point != point2:
                distances.append(distance(point2, point))
        while numpy.argmin(distances) in moves:
            distances.remove(distances[numpy.argmin(distances)])
        moves.append(numpy.argmin(distances))

    order = []
    order.append(0)
    currentContour=0

    for m in moves:
        order.append(moves[currentContour])
        currentContour = moves[currentContour]

    print(order)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.cTestButton.setGeometry(QtCore.QRect(330, 470, 121, 34))
        self.cTestButton.setObjectName("cTestButton")
        self.cTestButton.clicked.connect(connectionTest)
        self.beforeImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.beforeImage.setGeometry(QtCore.QRect(0, 0, 371, 441))
        self.beforeImage.setObjectName("beforeImage")
        self.afterImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.afterImage.setGeometry(QtCore.QRect(430, 0, 371, 441))
        self.afterImage.setObjectName("afterImage")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(110, 470, 111, 34))
        self.openButton.setObjectName("openButton")
        self.openButton.clicked.connect(openImage)
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setGeometry(QtCore.QRect(110, 510, 111, 34))
        self.processButton.setObjectName("processButton")
        self.processButton.clicked.connect(processImage)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 440, 101, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 440, 111, 18))
        self.label_4.setObjectName("label_4")
        self.tweakButton = QtWidgets.QPushButton(self.centralwidget)
        self.tweakButton.setGeometry(QtCore.QRect(580, 470, 101, 34))
        self.tweakButton.setObjectName("tweakButton")
        self.tweakButton.clicked.connect(tweakImage)
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(580, 510, 101, 34))
        self.drawButton.setObjectName("drawButton")
        self.drawButton.clicked.connect(drawImage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cTestButton.setText(_translate("MainWindow", "Connection Test"))
        self.openButton.setText(_translate("MainWindow", "Open Image"))
        self.processButton.setText(_translate("MainWindow", "Process Image"))
        self.label_3.setText(_translate("MainWindow", "Original Image"))
        self.label_4.setText(_translate("MainWindow", "Processed Image"))
        self.tweakButton.setText(_translate("MainWindow", "Tweak Image"))
        self.drawButton.setText(_translate("MainWindow", "Draw Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
