# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.cTestButton.setGeometry(QtCore.QRect(330, 470, 121, 34))
        self.cTestButton.setObjectName("cTestButton")
        self.beforeImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.beforeImage.setGeometry(QtCore.QRect(0, 0, 371, 441))
        self.beforeImage.setObjectName("beforeImage")
        self.afterImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.afterImage.setGeometry(QtCore.QRect(430, 0, 371, 441))
        self.afterImage.setObjectName("afterImage")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(110, 470, 111, 34))
        self.openButton.setObjectName("openButton")
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setGeometry(QtCore.QRect(110, 510, 111, 34))
        self.processButton.setObjectName("processButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 440, 101, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 440, 111, 18))
        self.label_4.setObjectName("label_4")
        self.tweakButton = QtWidgets.QPushButton(self.centralwidget)
        self.tweakButton.setGeometry(QtCore.QRect(580, 470, 101, 34))
        self.tweakButton.setObjectName("tweakButton")
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(580, 510, 101, 34))
        self.drawButton.setObjectName("drawButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cTestButton.setText(_translate("MainWindow", "Connection Test"))
        self.openButton.setText(_translate("MainWindow", "Open Image"))
        self.processButton.setText(_translate("MainWindow", "Process Image"))
        self.label_3.setText(_translate("MainWindow", "Original Image"))
        self.label_4.setText(_translate("MainWindow", "Processed Image"))
        self.tweakButton.setText(_translate("MainWindow", "Tweak Image"))
        self.drawButton.setText(_translate("MainWindow", "Draw Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
